framework: mocha

postMerge:
  pattern:
    - "test/*.spec.ts"
preMerge:
  pattern:
    - "test/*.spec.ts"
preRun:
     command:
        - npm install
        - npm run tsc

smartRun: false

configFile: "mocha-config/puppeteer-unit-tests.js"
version: 1.0.0